### ISSUE TITLE
Creating with aggregates supported ?

### ISSUE THREAD

**Issue by bilby91** [janjiss/rom_factory#2]
Hi, is  aggregate creation supported ?

Thanks!

**Comment by janjiss** [comment]
Hi! No, at this point it is not supported. If you are interested in this feature - Can you please describe it in more detail on how would you use it or point me to corresponding functionality in factory_girl? 

Would appreciate it

**Comment by bilby91** [comment]
@janjiss Will do it this week! Thanks!

**Comment by bilby91** [comment]
@janjiss I was referring to associations when I said `aggregates`. So, in `factory_girl` you can do something like this in your factories.

```
factory :post do
  # ...
  author
end
```

This will create a post model and also a author model that will be associated with the post. Do you think this can add value to `rom_factory` ?

For example, I have a use case where I need to create a User model and an AccessToken model that is associated with the user. It would be nice to be able to do with just one "factory call".

**Comment by bilby91** [comment]
Closing since repo was moved.
