### ISSUE TITLE
Add support for ROM Mappers

### ISSUE THREAD

**Issue by bilby91** [janjiss/rom_factory#3]
It would be a good idea to support ROM Mappers for entities.

So, when you do:

```
let(:user) { RomFactory::Builder.create(:user) }
```

it returns a new User instead of a `RomFactory::Struct`. What do you think @janjiss ?

**Comment by janjiss** [comment]
Well, the thing is, that ROM has no notion of User, unless you specifically map it to an object in Repository and ROM factory does not have a dependency on ROM repos. And, I think in most cases, people tend to use plain objects with ROM anyways.
All things aside, I am willing to discuss any ideas :)

**Comment by bilby91** [comment]
@janjiss Thanks for answering!

I understand your point! I was thinking on providing an extra option to `factory` method to perform the mapping. In my head I had something like this:

```
RomFactory::Builder.define do |b|
  b.factory(relation: :users, name: :user, mapper: :user) do |f| # I don't know if we need to register the mapping or we can look it up.
    f.name 'Test'
    f.email  'test@test.com'
    f.encrypted_password 'password'
  end
end
```

This should return the entity associated with the `:user` mapper. 

Let me know what do you think.

**Comment by janjiss** [comment]
I am thinking that this might actually work, but I would like to have it as an optional dependency. Let me play around with this a little bit and I will let you know what I find :)

**Comment by bilby91** [comment]
@janjiss Awesome! Just let me know! I can help you out with this! I just started playing with all the `rom` and `dry` ecosystem and I'm really interested in it.

**Comment by bilby91** [comment]
@janjiss Did you have a change to play with the mappers ?

**Comment by bilby91** [comment]
Closing since repo was moved.
