### ISSUE TITLE
Move to rom-rb?

### ISSUE THREAD

**Issue by solnic** [janjiss/rom_factory#8]
Hey, first of all - thank you for kick-starting this project. We're using it at Icelab, and it's been helpful. I started making some tweaks and improvements, and started wondering if you'd be interested in moving this project over to rom-rb organization, so that we can work on it together and increase its visibility. This is a crucial part of the stack and it'd be good to have it as an official gem in the org, and so that we can develop it faster.

Here's roughly what I'm thinking about in terms of improvements:

* rename it to rom-factory, because right now it doesn't follow rubygem naming conventions
* improve DSL so it's easier to use (we've done it in a private project already, and would like to OSS it)
* add integration with faker (also done in our priv project)
* separate pure data generation from persistence, so we can generate data for structs too
* make generated structs compatible with dry-struct (or even add support for generating dry structs)
* add support for generating aggregates too (this one will be more tricky)

WDYT?

**Comment by janjiss** [comment]
@solnic Sounds awesome, what kind of things do you need from me to make this move?

**Comment by solnic** [comment]
I could just fork it to rom-rb/rom-factory and continue there, how does that sound?

**Comment by janjiss** [comment]
@solnic Sounds good, as soon as that is done, I can update README and point in to the rom organisation.

**Comment by ghost** [comment]
Awesome,
 Count on me to help.

2017-03-02 12:21 GMT-03:00 Jānis Miezītis <notifications@github.com>:

**Comment by janjiss** [comment]
@solnic Updated README with a link to new repo. If you have any requests open up the issue and I can implement those features.

**Comment by timriley** [comment]
I dunno if it's too late, but could we consider changing repo ownership to rom-rb organization rather than maintaining a fork going forward? Just seems neater to me.

**Comment by solnic** [comment]
@timriley transferring a repo is a bit of a hassle so I just forked it and renamed already (before seeing your comment)

**Comment by solnic** [comment]
@janjiss @thiagopecanha hey folks, I released rom-factory 0.4.0 with a bunch of new features and internal refactoring/clean up. Please check out [the changelog](https://github.com/rom-rb/rom-factory/blob/master/CHANGELOG.md). Let me know if you'd like to continue helping with it. This is a crucial piece in our stack so I'll be helping with it too on a regular basis. Cheers :)

**Comment by ghost** [comment]
@solnic , I am not able to see the changelog, its returning 404...

Yes I'd like to help too

**Comment by solnic** [comment]
@thiagopecanha cool! I've fixed the link to changelog
